In [2]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

### Create & Read

#### 1D Array

In [4]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.shape

(5,)

In [7]:
arr1.dtype

dtype('int32')

In [8]:
arr1.ndim

1

In [9]:
arr1.size

5

#### 2D Array

In [11]:
arr2 = np.array([[1,2,3], [3,4,6]])
arr2

array([[1, 2, 3],
       [3, 4, 6]])

In [12]:
arr2.ndim

2

In [14]:
arr2.shape # (row, col)

(2, 3)

In [15]:
arr2.dtype

dtype('int32')

In [16]:
arr2.size

6

### 3D Array

In [21]:
arr3 = np.array([[[1,2,3], [3,4,6]],[[34,56,21],[98,45,75]]])
arr3

array([[[ 1,  2,  3],
        [ 3,  4,  6]],

       [[34, 56, 21],
        [98, 45, 75]]])

In [22]:
arr3.ndim

3

In [23]:
arr3.shape

(2, 2, 3)

In [24]:
arr3.size

12

### Create Random Array

In [28]:
randomArr = np.random.rand(3,2,3)
randomArr

array([[[0.42556461, 0.57675566, 0.92527828],
        [0.43256523, 0.05953075, 0.32347864]],

       [[0.3832993 , 0.91180564, 0.45043329],
        [0.20472838, 0.82045371, 0.03002354]],

       [[0.46176095, 0.59076105, 0.22363175],
        [0.98585728, 0.50246114, 0.81468134]]])

In [29]:
randomArr.dtype

dtype('float64')

In [30]:
zeroes = np.zeros((3,2,3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [31]:
zeroes.ndim

3

In [32]:
full = np.full((3,2,3),9)
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [34]:
ones = np.ones((3,2,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [35]:
arr3

array([[[ 1,  2,  3],
        [ 3,  4,  6]],

       [[34, 56, 21],
        [98, 45, 75]]])

In [36]:
arr3[0]

array([[1, 2, 3],
       [3, 4, 6]])

In [40]:
arr3[0][0][1]

2

In [41]:
arr3[0:2]

array([[[ 1,  2,  3],
        [ 3,  4,  6]],

       [[34, 56, 21],
        [98, 45, 75]]])

In [42]:
arr3[0:1]

array([[[1, 2, 3],
        [3, 4, 6]]])

In [43]:
arr3[-1]

array([[34, 56, 21],
       [98, 45, 75]])

In [44]:
arr3[-2]

array([[1, 2, 3],
       [3, 4, 6]])

In [45]:
arr3[1][0][1]

56

In [46]:
arr3[1,0,1]

56

### Update & Delete

In [47]:
a1 = np.random.rand(2,3,2)
a2 = np.random.rand(2,3,2)
a1

array([[[0.86263949, 0.95084835],
        [0.07864713, 0.87024033],
        [0.30591453, 0.25070917]],

       [[0.0688385 , 0.25274915],
        [0.45973903, 0.50233349],
        [0.75661869, 0.85894816]]])

In [48]:
a2

array([[[0.71852189, 0.46072558],
        [0.438334  , 0.19976937],
        [0.58313217, 0.24997174]],

       [[0.29822237, 0.56144067],
        [0.92154083, 0.03342877],
        [0.4104293 , 0.22555625]]])

#### Basic Math Operations

In [49]:
np.add(a1,a2)

array([[[1.58116138, 1.41157394],
        [0.51698113, 1.07000969],
        [0.8890467 , 0.50068091]],

       [[0.36706087, 0.81418982],
        [1.38127987, 0.53576225],
        [1.16704799, 1.08450441]]])

In [51]:
np.subtract(a1,a2)

array([[[ 0.14411761,  0.49012277],
        [-0.35968687,  0.67047096],
        [-0.27721764,  0.00073744]],

       [[-0.22938387, -0.30869152],
        [-0.4618018 ,  0.46890472],
        [ 0.34618939,  0.63339191]]])

In [52]:
np.divide(a1,a2)

array([[[ 1.20057511,  2.06380628],
        [ 0.17942283,  4.35622511],
        [ 0.52460582,  1.00295008]],

       [[ 0.23082943,  0.45017962],
        [ 0.49888081, 15.02698218],
        [ 1.84348118,  3.80813279]]])

In [53]:
np.multiply(a1,a2)

array([[[0.61982536, 0.43808016],
        [0.03447371, 0.17384736],
        [0.1783886 , 0.06267021]],

       [[0.02052918, 0.14190365],
        [0.42366829, 0.01679239],
        [0.31053848, 0.19374113]]])

#### Statistical Operations

In [55]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,8)
log = np.log(25)
mins = np.min(a1)
max = np.max(a2)

In [56]:
sqrt

5.0

In [57]:
abs

2

In [58]:
power

256

In [59]:
log

3.2188758248682006

In [60]:
mins

0.06883849867573544

In [61]:
max

0.9215408325709713

#### Update

In [62]:
arr3

array([[[ 1,  2,  3],
        [ 3,  4,  6]],

       [[34, 56, 21],
        [98, 45, 75]]])

In [64]:
arr3[1,0,1] = 500

In [65]:
arr3

array([[[  1,   2,   3],
        [  3,   4,   6]],

       [[ 34, 500,  21],
        [ 98,  45,  75]]])

In [66]:
arr3.sort()

In [67]:
arr3

array([[[  1,   2,   3],
        [  3,   4,   6]],

       [[ 21,  34, 500],
        [ 45,  75,  98]]])

#### Reshape

In [68]:
arr3.shape

(2, 2, 3)

In [72]:
arr3_reshape = arr3.reshape((2,3,2))
arr3_reshape

array([[[  1,   2],
        [  3,   3],
        [  4,   6]],

       [[ 21,  34],
        [500,  45],
        [ 75,  98]]])

In [73]:
arr3.shape

(2, 2, 3)

#### Appending & Inserting

In [74]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [81]:
new_array = np.ones((3,2,3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [84]:
appd = np.append(zeroes,new_array, axis = 0) # axis 0 = row, axis 1 = column
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

##### Insert

In [85]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [86]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [88]:
inserted_array = np.insert(zeroes, 2, new_array, axis = 0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

#### Delete

In [89]:
arr4 = np.random.rand(3,2,3)
arr4

array([[[0.71197648, 0.49052591, 0.24879701],
        [0.64638607, 0.26061937, 0.68500585]],

       [[0.74691993, 0.55565488, 0.89166505],
        [0.49897908, 0.66566028, 0.45262307]],

       [[0.36202384, 0.02064169, 0.17393942],
        [0.96399779, 0.85782224, 0.20656729]]])

In [91]:
# Delete the array
arr5 = np.delete(arr4, 0, axis=1)

In [92]:
arr5

array([[[0.64638607, 0.26061937, 0.68500585]],

       [[0.49897908, 0.66566028, 0.45262307]],

       [[0.96399779, 0.85782224, 0.20656729]]])

In [93]:
np.save("New_Array",arr5)

In [94]:
np.load("New_Array.npy")

array([[[0.64638607, 0.26061937, 0.68500585]],

       [[0.49897908, 0.66566028, 0.45262307]],

       [[0.96399779, 0.85782224, 0.20656729]]])